name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    # 核心配置：设置定时任务
    # cron 表达式 '0 0 * * *' 代表每天在 UTC 时间的零点 (也就是北京时间上午8点) 运行一次。
    - cron: "0 0 * * *"
  # 保留手动触发功能，让您随时可以点击按钮立即更新。
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # 步骤 1: 检出您的仓库代码
      - name: Checkout target repo
        uses: actions/checkout@v3

      # 步骤 2: 运行同步 Action，它会自动从上游仓库拉取最新代码
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          # 注意：即使原项目改名为 NextChat，这里的上游仓库地址也无需修改，它会自动处理。
          upstream_sync_repo: ChatGPTNextWeb/ChatGPT-Next-Web
          upstream_sync_branch: main
          target_sync_branch: main
          # 使用 GitHub 自动生成的 Token，安全且无需您手动配置。
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      # 步骤 3: 检查同步是否失败，并给出提示
      - name: Sync check
        if: failure()
        run: |
          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#%E6%89%93%E5%BC%80%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0"
          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the detailed tutorial for instructions: https://github.com/Yidadaa/ChatGPT-Next-Web#enable-automatic-updates"
          exit 1
